name: Application Deployment

on:
  workflow_run:
    workflows: ["Infrastructure Deployment"]
    types:
      - completed

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::731629701372:role/task-management-dev-github-actions-deploy-role
          aws-region: eu-west-1

      - name: Login to ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push images
        run: |
          docker build -t ${{ steps.ecr.outputs.registry }}/task-management-dev-backend:${{ github.event.workflow_run.head_sha }}-${{ github.run_attempt }} ./backend
          docker push ${{ steps.ecr.outputs.registry }}/task-management-dev-backend:${{ github.event.workflow_run.head_sha }}-${{ github.run_attempt }}

          docker build -t ${{ steps.ecr.outputs.registry }}/task-management-dev-frontend:${{ github.event.workflow_run.head_sha }}-${{ github.run_attempt }} ./frontend
          docker push ${{ steps.ecr.outputs.registry }}/task-management-dev-frontend:${{ github.event.workflow_run.head_sha }}-${{ github.run_attempt }}

      - name: Deploy backend
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        id: backend
        with:
          task-definition-family: task-management-dev-backend
          container-name: backend
          image: ${{ steps.ecr.outputs.registry }}/task-management-dev-backend:${{ github.event.workflow_run.head_sha }}-${{ github.run_attempt }}

      - uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.backend.outputs.task-definition }}
          service: task-management-dev-backend-service
          cluster: task-management-dev-ecs-cluster

      - name: Deploy frontend
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        id: frontend
        with:
          task-definition-family: task-management-dev-frontend
          container-name: frontend
          image: ${{ steps.ecr.outputs.registry }}/task-management-dev-frontend:${{ github.event.workflow_run.head_sha }}-${{ github.run_attempt }}

      - uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.frontend.outputs.task-definition }}
          service: task-management-dev-frontend-service
          cluster: task-management-dev-ecs-cluster

      - name: Start services
        run: |
          aws ecs update-service --cluster task-management-dev-ecs-cluster --service task-management-dev-backend-service --desired-count 1 --region eu-west-1
          aws ecs update-service --cluster task-management-dev-ecs-cluster --service task-management-dev-frontend-service --desired-count 1 --region eu-west-1