name: Continuous Integration

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::731629701372:role/task-management-dev-github-actions-deploy-role
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push backend image
        run: |
          docker build \
            -t ${{ steps.login-ecr.outputs.registry }}/task-management-dev-backend:${{ github.sha }} \
            ./backend

          docker push \
            ${{ steps.login-ecr.outputs.registry }}/task-management-dev-backend:${{ github.sha }}

      - name: Build and push frontend image
        run: |
          docker build \
            -t ${{ steps.login-ecr.outputs.registry }}/task-management-dev-frontend:${{ github.sha }} \
            ./frontend

          docker push \
            ${{ steps.login-ecr.outputs.registry }}/task-management-dev-frontend:${{ github.sha }}
