on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::731629701372:role/task-management-dev-github-actions-deploy-role
          aws-region: eu-west-1

      - uses: aws-actions/amazon-ecr-login@v2

      - run: |
          BACKEND_IMAGE="731629701372.dkr.ecr.eu-west-1.amazonaws.com/task-management-dev-backend:${GITHUB_SHA}"
          FRONTEND_IMAGE="731629701372.dkr.ecr.eu-west-1.amazonaws.com/task-management-dev-frontend:${GITHUB_SHA}"

          docker build -t "${BACKEND_IMAGE}" backend
          docker push "${BACKEND_IMAGE}"

          docker build -t "${FRONTEND_IMAGE}" frontend
          docker push "${FRONTEND_IMAGE}"

      - run: |
          BACKEND_TASK_DEFINITION="$(aws ecs describe-services \
            --cluster task-management-dev-ecs-cluster \
            --services task-management-dev-backend-service \
            --query 'services[0].taskDefinition' \
            --output text)"

          aws ecs describe-task-definition \
            --task-definition "${BACKEND_TASK_DEFINITION}" \
            --query taskDefinition \
            > backend-task-definition.json

          FRONTEND_TASK_DEFINITION="$(aws ecs describe-services \
            --cluster task-management-dev-ecs-cluster \
            --services task-management-dev-frontend-service \
            --query 'services[0].taskDefinition' \
            --output text)"

          aws ecs describe-task-definition \
            --task-definition "${FRONTEND_TASK_DEFINITION}" \
            --query taskDefinition \
            > frontend-task-definition.json

      - id: backend-task
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: backend-task-definition.json
          container-name: backend
          image: 731629701372.dkr.ecr.eu-west-1.amazonaws.com/task-management-dev-backend:${{ github.sha }}

      - uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.backend-task.outputs.task-definition }}
          service: task-management-dev-backend-service
          cluster: task-management-dev-ecs-cluster

      - id: frontend-task
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: frontend-task-definition.json
          container-name: frontend
          image: 731629701372.dkr.ecr.eu-west-1.amazonaws.com/task-management-dev-frontend:${{ github.sha }}

      - uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.frontend-task.outputs.task-definition }}
          service: task-management-dev-frontend-service
          cluster: task-management-dev-ecs-cluster
