name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: Type destroy to confirm infrastructure destruction
        required: true
        type: string

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: eu-west-1
  AWS_ROLE_ARN: arn:aws:iam::731629701372:role/task-management-terraform-role

  TERRAFORM_VERSION: 1.13.3
  TF_IN_AUTOMATION: true
  TF_INPUT: false

  TF_STATE_BUCKET: task-management-platform-state-lock-eu-west-1
  TF_STATE_KEY: task-management/dev/terraform.tfstate

jobs:
  destroy:
    name: Destroy development infrastructure
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main' && inputs.confirmation == 'destroy'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Check Terraform formatting
        run: terraform fmt -check -recursive infra/terraform

      - name: Initialize Terraform
        run: |
          terraform -chdir=infra/terraform/environments/dev init \
            -reconfigure \
            -backend-config="bucket=${TF_STATE_BUCKET}" \
            -backend-config="key=${TF_STATE_KEY}" \
            -backend-config="region=${AWS_REGION}" \
            -backend-config="encrypt=true" \
            -backend-config="use_lockfile=true"

      - name: Validate Terraform
        run: terraform -chdir=infra/terraform/environments/dev validate

      - name: Create Terraform destroy plan
        run: |
          terraform -chdir=infra/terraform/environments/dev plan \
            -destroy \
            -lock-timeout=5m \
            -out=destroy.tfplan

      - name: Apply Terraform destroy plan
        run: |
          terraform -chdir=infra/terraform/environments/dev apply \
            -lock-timeout=5m \
            destroy.tfplan