name: Infrastructure Destroy

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: Type DESTROY to confirm infrastructure destruction
        required: true
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  destroy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra/terraform/environments/dev

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Confirm destroy
        if: inputs.confirmation != 'DESTROY'
        run: exit 1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::731629701372:role/task-management-terraform-role
          aws-region: eu-west-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.13.3"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve