name: Terraform Deployment

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: eu-west-1
  AWS_ROLE_ARN: arn:aws:iam::731629701372:role/task-management-terraform-role

jobs:
  deploy:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    defaults:
      run:
        working-directory: infra/terraform/environments/dev

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform format
        working-directory: infra/terraform
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -out=tfplan

      - name: Terraform apply
        run: terraform apply tfplan
